export const languages = {
    'Srpski': {
        grabYourFavorite: 'Izaberite svoju omiljenu',
        donut: 'Krofnu',
        mainSubtitle: 'Domaće krofne sa neverovatnim različitim topinzima, bez dodatnih aditiva i šećera.',
        orderNow: 'Poručite odmah!',
        home: 'Početna',
        shop: 'Prodavnica',
        aboutUs: 'O nama',
        contact: 'Kontakt',
        createDonut: 'Kreiraj krofnu',
        createBox: 'Kreiraj kutiju',
        description1: 'Lagana i prozračna krofna, punjena glatkom vanil kremom i prekrivena nežnim vanil prelivom. Jednostavan, ali klasičan izbor za one koji vole suptilne ukuse.',
        description2: 'Sočna krofna punjena jagodastim kremom, prekrivena savršenim roze jagodastim prelivom i ukrašena svežim bobicama za dodatni talas ukusa.',
        description3: 'Slatka krofna punjena karamelom sa mekanom i puterastom podlogom, prekrivena karamel prelivom i završnim prelivom obogaćenim karamel sosom. Konačni užitak za ljubitelje karamele.',
        description4: 'Bogata i luksuzna krofna punjena baršunastom čokoladnim kremom, prekrivena glatkim čokoladnim prelivom i prelivena dodatnom otopljenom čokoladom. Pravi san za ljubitelje čokolade!',
        description5: 'Slatka i voćna poslastica, ova krofna je punjena svežim džemom od jagoda i prekrivena jagodastim prelivom. Savršen balans slatkoće i kiselkosti u svakom zalogaju.',
        description6: 'Ova krofna je savršena harmonija dva klasična ukusa. Punjena i vanilin kremom i čokoladnim kremom, a zatim prekrivena spiralom čokoladne i vanilin glazure, za savršen zalogaj svaki put.',
        description7: 'Najbolje iz oba sveta! Mekana krofna punjena divnom mešavinom svežeg džema od jagoda i kremaste čokoladne ganache, prekrivena spiralom čokoladnog i jagodastog preliva.',
        description8: 'Savršen balans crne i mlečne čokolade, ova krofna ima mekanu čokoladnu podlogu, luksuzno punjenje od čokoladnih trufli i sjajni čokoladni preliv.',
        description9: 'Doživite mekoću ove vazdušaste krofne koja se topi u ustima, punjenu vanilin kremom i posutu prah šećerom za savršen užitak.',
        description10: 'Ova krofna je dvostruka poslastica! Meka, vazdušasta krofna punjena dekadentnim čokoladnim filom, zatim umočena u gusti sloj čokoladnog preliva za ultimativno čokoladno iskustvo.',
        addToCart: 'Dodaj u korpu',
        quote: '"Gde svaka krofna govori priču <br/> o kvalitetu i pažnji."',
        quality: 'U Sweet Circle-u, naše krofne se prave sa najvećom pažnjom, koristeći samo najsvežije i najkvalitetnije sastojke. Svaka krofna se ručno pravi, čime se osigurava savršenstvo u svakom zalogaju.',
        naturalIngredients: 'Naše krofne su napravljene od prirodnih sastojaka – bez dodataka i veštačkih aditiva. Koristimo organske i lokalne proizvode kako bismo garantovali najbolji mogući ukus i zdravstvene koristi u svakom zalogaju.',
        noAddedSugar: 'U Sweet Circle-u, ne koristimo rafinisani šećer. Naše krofne su zaslađene prirodnim alternativama, nudeći ukusan, a opet zdrav užitak bez viška kalorija i šećera.',
        name: 'Ime',
        email: 'E-mail',
        phone: 'Broj telefona', 
        address: 'Adresa',
        message: 'Poruka',
        sendForm: 'Pošalji formu',
        ourAddress: 'Naša adresa',
        ourContact: 'Naš kontakt',
        followUs: 'Prati nas',
        boxSize: 'Izaberi svoju <br/> veličinu kutije!',
        box3: 'Kutija od 3 krofne',
        box6: 'Kutija od 6 krofni',
        box10: 'Kutija od 10 krofni',
        addedDonuts: 'Dodate Krofne:',
        text1: 'Lagana i prozračna krofna, punjena glatkom vanil kremom i prekrivena nežnim vanil prelivom. Jednostavan, ali klasičan izbor za one koji vole suptilne ukuse.',
        text2: 'Sočna krofna punjena jagodastim kremom, prekrivena savršenim roze jagodastim prelivom i ukrašena svežim bobicama za dodatni talas ukusa.',
        text3: 'Slatka krofna punjena karamelom sa mekanom i puterastom podlogom, prekrivena karamel prelivom i završnim prelivom obogaćenim karamel sosom. Konačni užitak za ljubitelje karamele.',
        text4: 'Bogata i luksuzna krofna punjena baršunastom čokoladnim kremom, prekrivena glatkim čokoladnim prelivom i prelivena dodatnom otopljenom čokoladom. Pravi san za ljubitelje čokolade!',
        text5: 'Slatka i voćna poslastica, ova krofna je punjena svežim džemom od jagoda i prekrivena jagodastim prelivom. Savršen balans slatkoće i kiselkosti u svakom zalogaju.',
        text6: 'Ova krofna je savršena harmonija dva klasična ukusa. Punjena i vanilin kremom i čokoladnim kremom, a zatim prekrivena spiralom čokoladne i vanilin glazure, za savršen zalogaj svaki put.',
        text7: 'Najbolje iz oba sveta! Mekana krofna punjena divnom mešavinom svežeg džema od jagoda i kremaste čokoladne ganache, prekrivena spiralom čokoladnog i jagodastog preliva.',
        text8: 'Savršen balans crne i mlečne čokolade, ova krofna ima mekanu čokoladnu podlogu, luksuzno punjenje od čokoladnih trufli i sjajni čokoladni preliv.',
        text9: 'Doživite mekoću ove vazdušaste krofne koja se topi u ustima, punjenu vanilin kremom i posutu prah šećerom za savršen užitak.',
        text10: 'Ova krofna je dvostruka poslastica! Meka, vazdušasta krofna punjena dekadentnim čokoladnim filom, zatim umočena u gusti sloj čokoladnog preliva za ultimativno čokoladno iskustvo.',
    },  
    'English': {
        grabYourFavorite: 'Grab your favorite',
        donut: 'Donut',
        mainSubtitle: 'Homemade doughnuts with an incredible variety of toppings and toppings without the use of artificial additives, colors or flavors.',
        orderNow: 'Order Now!',
        home: 'Home',
        shop: 'Shop',
        aboutUs: 'About Us',
        contact: 'Contact',
        createDonut: 'Create Donut',
        createBox: 'Create Box',
        description1: 'A light and fluffy donut filled with smooth vanilla cream and topped with a delicate vanilla glaze. A simple yet classic choice for those who love subtle flavors.',
        description2: 'A luscious donut filled with strawberry cream, covered with a vibrant pink strawberry glaze, and topped with fresh berries for an extra burst of flavor.',
        description3: 'A sweet, caramel-filled donut with a soft and buttery base, topped with a caramel glaze and finished with a drizzle of rich caramel sauce. The ultimate indulgence for caramel lovers.',
        description4: "A rich and indulgent donut filled with velvety chocolate cream, topped with a smooth chocolate glaze and drizzled with extra melted chocolate. A true chocolate lover's dream!",
        description5: 'A sweet and fruity treat, this donut is filled with fresh strawberry jam and topped with a strawberry glaze. The perfect balance of sweetness and tartness in every bite.',
        description6: 'This donut is the perfect harmony of two classic flavors. Filled with both vanilla custard and chocolate cream, then topped with a swirl of chocolate and vanilla icing for a balanced bite every time.',
        description7: 'The best of both worlds! A soft donut filled with a delightful mix of fresh strawberry jam and creamy chocolate ganache, topped with a swirl of chocolate and strawberry glaze.',
        description8: 'A perfect balance of dark and milk chocolate, this donut features a soft chocolate base with a luxurious chocolate truffle filling and a glossy chocolate glaze.',
        description9: 'Experience the soft, melt-in-your-mouth goodness of this airy donut, filled with vanilla custard and topped with a dusting of powdered sugar for a perfect finish.',
        description10: 'This donut is a double treat! A soft, fluffy doughnut stuffed with a decadent chocolate filling, then dipped in a thick layer of chocolate glaze for the ultimate chocolate experience.',
        addToCart: 'Add to cart',
        quote: '"Where every donut tells a <br/> story of quality and care."',
        quality: 'At Sweet Circle, our donuts are made with the utmost care, using only the freshest and highest-quality ingredients. Each donut is crafted by hand, ensuring perfection in every bite.',
        naturalIngredients: 'Our donuts are made with natural ingredients – free from additives and artificial additives. We use organic and locally sourced products to guarantee the best possible taste and health benefits in every bite.',
        noAddedSugar: 'At Sweet Circle, we don’t use refined sugar. Our donuts are sweetened with natural alternatives, offering a delicious yet healthy treat without excess calories and sugar.',
        name: 'Name',
        email: 'E-mail',
        phone: 'Phone', 
        address: 'Address',
        message: 'Message',
        sendForm: 'Send Form',
        ourAddress: 'Our Address',
        ourContact: 'Our Contact',
        followUs: 'Follow us',
        boxSize: 'Choose your <br/> box size!',
        box3: 'Box of 3 donuts',
        box6: 'Box of 6 donuts',
        box10: 'Box of 10 donuts',
        addedDonuts: 'Added Donuts:',
        text1: 'A light and fluffy donut filled with smooth vanilla cream and topped with a delicate vanilla glaze. A simple yet classic choice for those who love subtle flavors.',
        text2: 'A luscious donut filled with strawberry cream, covered with a vibrant pink strawberry glaze, and topped with fresh berries for an extra burst of flavor.',
        text3: 'A sweet, caramel-filled donut with a soft and buttery base, topped with a caramel glaze and finished with a drizzle of rich caramel sauce. The ultimate indulgence for caramel lovers.',
        text4: "A rich and indulgent donut filled with velvety chocolate cream, topped with a smooth chocolate glaze and drizzled with extra melted chocolate. A true chocolate lover's dream!",
        text5: 'A sweet and fruity treat, this donut is filled with fresh strawberry jam and topped with a strawberry glaze. The perfect balance of sweetness and tartness in every bite.',
        text6: 'This donut is the perfect harmony of two classic flavors. Filled with both vanilla custard and chocolate cream, then topped with a swirl of chocolate and vanilla icing for a balanced bite every time.',
        text7: 'The best of both worlds! A soft donut filled with a delightful mix of fresh strawberry jam and creamy chocolate ganache, topped with a swirl of chocolate and strawberry glaze.',
        text8: 'A perfect balance of dark and milk chocolate, this donut features a soft chocolate base with a luxurious chocolate truffle filling and a glossy chocolate glaze.',
        text9: 'Experience the soft, melt-in-your-mouth goodness of this airy donut, filled with vanilla custard and topped with a dusting of powdered sugar for a perfect finish.',
        text10: 'This donut is a double treat! A soft, fluffy doughnut stuffed with a decadent chocolate filling, then dipped in a thick layer of chocolate glaze for the ultimate chocolate experience.',
    },
    'Deutsch': {
        grabYourFavorite: 'Wählen Sie Ihre Lieblingssorte',
        donut: 'Den Donut',
        mainSubtitle: 'Hausgemachte Donuts mit unglaublichen, verschiedenen Toppings, ohne zusätzliche Zusatzstoffe und Zucker.',
        orderNow: 'Bestellen Sie sofort!',
        home: 'Startseite',
        shop: 'Shop',
        aboutUs: 'Über uns',
        contact: 'Kontakt',
        createDonut: 'Kreiere deinen Donut',
        createBox: 'Kreiere deine Box',
        description1: 'Ein leichter und luftiger Donut, gefüllt mit glatter Vanillecreme und überzogen mit zartem Vanilleglasur. Eine einfache, aber klassische Wahl für diejenigen, die subtile Aromen lieben.',
        description2: 'Ein saftiger Donut, gefüllt mit Erdbeercreme, überzogen mit lebendig pinkfarbener Erdbeerglasur und garniert mit frischen Beeren für einen zusätzlichen Geschmackskick.',
        description3: 'Ein süßer Donut, gefüllt mit Karamell, mit einem weichen und buttrigen Boden, überzogen mit Karamellglasur und veredelt mit einem Drizzle aus reichhaltiger Karamellsauce. Der ultimative Genuss für Karamell-Liebhaber.',
        description4: 'Ein reichhaltiger und luxuriöser Donut, gefüllt mit samtiger Schokoladencreme, überzogen mit glatter Schokoladenglasur und garniert mit zusätzlicher geschmolzener Schokolade. Ein wahrer Traum für Schokoladenliebhaber!',
        description5: 'Eine süße und fruchtige Leckerei, dieser Donut ist gefüllt mit frischer Erdbeermarmelade und überzogen mit Erdbeerglasur. Die perfekte Balance von Süße und Säure in jedem Bissen.',
        description6: 'Dieser Donut ist die perfekte Harmonie zweier klassischer Geschmacksrichtungen. Gefüllt mit Vanillepudding und Schokoladencreme, dann überzogen mit einem Wirbel aus Schokoladen- und Vanilleglasur für einen ausgewogenen Bissen bei jedem Mal.',
        description7: 'Das Beste aus beiden Welten! Ein weicher Donut, gefüllt mit einer köstlichen Mischung aus frischer Erdbeermarmelade und cremiger Schokoladenganache, überzogen mit einem Wirbel aus Schokoladen- und Erdbeerglasur.',
        description8: 'Die perfekte Balance zwischen dunkler und Milchschokolade, dieser Donut hat einen weichen Schokoladenboden, eine luxuriöse Schokoladentrüffelfüllung und eine glänzende Schokoladenglasur.',
        description9: 'Erleben Sie die Weichheit dieses luftigen Donuts, der im Mund schmilzt, gefüllt mit Vanillecreme und mit Puderzucker bestäubt für den perfekten Abschluss.',
        description10: 'Dieser Donut ist ein doppelter Genuss! Ein weicher, luftiger Donut, gefüllt mit einer dekadenten Schokoladenfüllung, dann in eine dicke Schicht Schokoladenglasur getaucht für das ultimative Schokoladen-Erlebnis.',
        addToCart: 'In den Korb',
        quote: '"Wo jeder Donut eine Geschichte <br/> von Qualität und Fürsorge erzählt."',
        quality: 'Bei Sweet Circle werden unsere Donuts mit größter Sorgfalt hergestellt, unter Verwendung der frischesten und hochwertigsten Zutaten. Jeder Donut wird von Hand gefertigt, um Perfektion in jedem Bissen zu gewährleisten.',
        naturalIngredients: 'Unsere Donuts werden aus natürlichen Zutaten hergestellt – ohne Zusatzstoffe und künstliche Zusätze. Wir verwenden biologische und lokal bezogene Produkte, um den bestmöglichen Geschmack und gesundheitliche Vorteile in jedem Bissen zu garantieren.',
        noAddedSugar: 'Bei Sweet Circle verwenden wir keinen raffinierten Zucker. Unsere Donuts sind mit natürlichen Alternativen gesüßt und bieten eine leckere, aber dennoch gesunde Leckerei ohne überschüssige Kalorien und Zucker.',
        name: 'Name',
        email: 'E-Mail',
        phone: 'Telefon', 
        address: 'Adresse',
        message: 'Nachricht',
        sendForm: 'Formular absenden',
        ourAddress: 'Unsere Adresse',
        ourContact: 'Unsere Kontakt',
        followUs: 'Folge uns',
        boxSize: 'Wählen Sie <br/> Ihre Boxgröße!',
        box3: 'Box mit 3 Donuts',
        box6: 'Box mit 6 Donuts',
        box10: 'Box mit 10 Donuts',
        addedDonuts: 'Donuts hinzu:',
        text1: 'Ein leichter und luftiger Donut, gefüllt mit glatter Vanillecreme und überzogen mit zartem Vanilleglasur. Eine einfache, aber klassische Wahl für diejenigen, die subtile Aromen lieben.',
        text2: 'Ein saftiger Donut, gefüllt mit Erdbeercreme, überzogen mit lebendig pinkfarbener Erdbeerglasur und garniert mit frischen Beeren für einen zusätzlichen Geschmackskick.',
        text3: 'Ein süßer Donut, gefüllt mit Karamell, mit einem weichen und buttrigen Boden, überzogen mit Karamellglasur und veredelt mit einem Drizzle aus reichhaltiger Karamellsauce. Der ultimative Genuss für Karamell-Liebhaber.',
        text4: 'Ein reichhaltiger und luxuriöser Donut, gefüllt mit samtiger Schokoladencreme, überzogen mit glatter Schokoladenglasur und garniert mit zusätzlicher geschmolzener Schokolade. Ein wahrer Traum für Schokoladenliebhaber!',
        text5: 'Eine süße und fruchtige Leckerei, dieser Donut ist gefüllt mit frischer Erdbeermarmelade und überzogen mit Erdbeerglasur. Die perfekte Balance von Süße und Säure in jedem Bissen.',
        text6: 'Dieser Donut ist die perfekte Harmonie zweier klassischer Geschmacksrichtungen. Gefüllt mit Vanillepudding und Schokoladencreme, dann überzogen mit einem Wirbel aus Schokoladen- und Vanilleglasur für einen ausgewogenen Bissen bei jedem Mal.',
        text7: 'Das Beste aus beiden Welten! Ein weicher Donut, gefüllt mit einer köstlichen Mischung aus frischer Erdbeermarmelade und cremiger Schokoladenganache, überzogen mit einem Wirbel aus Schokoladen- und Erdbeerglasur.',
        text8: 'Die perfekte Balance zwischen dunkler und Milchschokolade, dieser Donut hat einen weichen Schokoladenboden, eine luxuriöse Schokoladentrüffelfüllung und eine glänzende Schokoladenglasur.',
        text9: 'Erleben Sie die Weichheit dieses luftigen Donuts, der im Mund schmilzt, gefüllt mit Vanillecreme und mit Puderzucker bestäubt für den perfekten Abschluss.',
        text10: 'Dieser Donut ist ein doppelter Genuss! Ein weicher, luftiger Donut, gefüllt mit einer dekadenten Schokoladenfüllung, dann in eine dicke Schicht Schokoladenglasur getaucht für das ultimative Schokoladen-Erlebnis.',
    }
}